language: ruby
rvm:
  - 2.2
script:
  - bundle exec rake clean package VERSION=$TRAVIS_TAG
  - bundle exec rake clean package OFFLINE=true PINNED=true VERSION=$TRAVIS_TAG
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: build/java-buildpack-*.zip
  skip_cleanup: true
  on:
    tags: true
